### ISSUE TITLE
Hijacker of my edit on stackoverflow

### ISSUE THREAD

**Issue by 1stthomas** [danbopes/mtgbot-website#5]
Why are you hijacking my edit on so?!??
See my edit: https://stackoverflow.com/review/suggested-edits/21201696
compare your edit: https://stackoverflow.com/posts/36011988/revisions

**Comment by danbopes** [comment]
You edited a 2 year-old off topic question, which caused an unneeded bump to the home page.

The critical issue with the post was the noise at the top: "I am a Laravel beginner; Please help me to solve this error.", which should have been removed completely. All the other stuff was just minor typos. Even [jigar](https://stackoverflow.com/users/861704/jigar) agreed that these were too minor to warrant an edit.
